// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _250828_universityTask.Data;

#nullable disable

namespace _250828_universityTask.Migrations.TryOutDb
{
    [DbContext(typeof(TryOutDbContext))]
    [Migration("20251006094920_student2 model added")]
    partial class student2modeladded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_250828_universityTask.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Student2Id")
                        .HasColumnType("int");

                    b.Property<int>("UniversityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Student2Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("Professors");
                });

            modelBuilder.Entity("_250828_universityTask.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProfessorAddedId")
                        .HasColumnType("int");

                    b.Property<int?>("UniversityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorAddedId");

                    b.HasIndex("UniversityId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("_250828_universityTask.Models.Student2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProfessorAddedId")
                        .HasColumnType("int");

                    b.Property<int?>("UniversityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorAddedId");

                    b.HasIndex("UniversityId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("_250828_universityTask.Models.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("_250828_universityTask.Models.Professor", b =>
                {
                    b.HasOne("_250828_universityTask.Models.Student2", null)
                        .WithMany("BelongingProfessors")
                        .HasForeignKey("Student2Id");

                    b.HasOne("_250828_universityTask.Models.University", "University")
                        .WithMany("Professors")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("_250828_universityTask.Models.Student", b =>
                {
                    b.HasOne("_250828_universityTask.Models.Professor", "ProfessorAdded")
                        .WithMany("AddedStudents")
                        .HasForeignKey("ProfessorAddedId");

                    b.HasOne("_250828_universityTask.Models.University", "University")
                        .WithMany("Students")
                        .HasForeignKey("UniversityId");

                    b.Navigation("ProfessorAdded");

                    b.Navigation("University");
                });

            modelBuilder.Entity("_250828_universityTask.Models.Student2", b =>
                {
                    b.HasOne("_250828_universityTask.Models.Professor", "ProfessorAdded")
                        .WithMany()
                        .HasForeignKey("ProfessorAddedId");

                    b.HasOne("_250828_universityTask.Models.University", "University")
                        .WithMany()
                        .HasForeignKey("UniversityId");

                    b.Navigation("ProfessorAdded");

                    b.Navigation("University");
                });

            modelBuilder.Entity("_250828_universityTask.Models.Professor", b =>
                {
                    b.Navigation("AddedStudents");
                });

            modelBuilder.Entity("_250828_universityTask.Models.Student2", b =>
                {
                    b.Navigation("BelongingProfessors");
                });

            modelBuilder.Entity("_250828_universityTask.Models.University", b =>
                {
                    b.Navigation("Professors");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
