// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _250828_universityTask.Data;

#nullable disable

namespace _250828_universityTask.Migrations.TryOutDb
{
    [DbContext(typeof(TryOutDbContext))]
    partial class TryOutDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProfessorStudent2", b =>
                {
                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<int>("Student2Id")
                        .HasColumnType("int");

                    b.HasKey("ProfessorId", "Student2Id");

                    b.HasIndex("Student2Id");

                    b.ToTable("ProfessorStudent2");

                    b.HasData(
                        new
                        {
                            ProfessorId = 1,
                            Student2Id = 1
                        },
                        new
                        {
                            ProfessorId = 2,
                            Student2Id = 1
                        },
                        new
                        {
                            ProfessorId = 1,
                            Student2Id = 2
                        },
                        new
                        {
                            ProfessorId = 4,
                            Student2Id = 2
                        },
                        new
                        {
                            ProfessorId = 1,
                            Student2Id = 3
                        },
                        new
                        {
                            ProfessorId = 4,
                            Student2Id = 3
                        });
                });

            modelBuilder.Entity("_250828_universityTask.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UniversityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("Professors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "klaus@example.com",
                            Name = "Klaus Mikaelson",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "tim@example.com",
                            Name = "Tim McGraw",
                            UniversityId = 3
                        },
                        new
                        {
                            Id = 3,
                            Email = "sophia@example.com",
                            Name = "Sophia Goldberg",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 4,
                            Email = "clara@example.com",
                            Name = "Clara Bow",
                            UniversityId = 2
                        });
                });

            modelBuilder.Entity("_250828_universityTask.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProfessorAddedId")
                        .HasColumnType("int");

                    b.Property<int?>("UniversityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorAddedId");

                    b.HasIndex("UniversityId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("_250828_universityTask.Models.Student2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProfessorAddedId")
                        .HasColumnType("int");

                    b.Property<int?>("UniversityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorAddedId");

                    b.HasIndex("UniversityId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Addison Montgomery",
                            ProfessorAddedId = 4,
                            UniversityId = 2
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hanna Marin",
                            ProfessorAddedId = 2,
                            UniversityId = 3
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mark Sloan",
                            ProfessorAddedId = 1,
                            UniversityId = 1
                        });
                });

            modelBuilder.Entity("_250828_universityTask.Models.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Universities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Cambridge",
                            Country = "USA",
                            Name = "Massachusetts Institute of Technology (MIT)"
                        },
                        new
                        {
                            Id = 2,
                            City = "Stanford",
                            Country = "USA",
                            Name = "Stanford University"
                        },
                        new
                        {
                            Id = 3,
                            City = "London",
                            Country = "UK",
                            Name = "Imperial College London"
                        });
                });

            modelBuilder.Entity("ProfessorStudent2", b =>
                {
                    b.HasOne("_250828_universityTask.Models.Professor", null)
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_250828_universityTask.Models.Student2", null)
                        .WithMany()
                        .HasForeignKey("Student2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_250828_universityTask.Models.Professor", b =>
                {
                    b.HasOne("_250828_universityTask.Models.University", "University")
                        .WithMany("Professors")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("_250828_universityTask.Models.Student", b =>
                {
                    b.HasOne("_250828_universityTask.Models.Professor", "ProfessorAdded")
                        .WithMany("AddedStudents")
                        .HasForeignKey("ProfessorAddedId");

                    b.HasOne("_250828_universityTask.Models.University", "University")
                        .WithMany("Students")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ProfessorAdded");

                    b.Navigation("University");
                });

            modelBuilder.Entity("_250828_universityTask.Models.Student2", b =>
                {
                    b.HasOne("_250828_universityTask.Models.Professor", "ProfessorAdded")
                        .WithMany()
                        .HasForeignKey("ProfessorAddedId");

                    b.HasOne("_250828_universityTask.Models.University", "University")
                        .WithMany()
                        .HasForeignKey("UniversityId");

                    b.Navigation("ProfessorAdded");

                    b.Navigation("University");
                });

            modelBuilder.Entity("_250828_universityTask.Models.Professor", b =>
                {
                    b.Navigation("AddedStudents");
                });

            modelBuilder.Entity("_250828_universityTask.Models.University", b =>
                {
                    b.Navigation("Professors");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
